/**
 * GAME STATES FOR THE IN GAME TEXT. GAME TEXT STATE.
 */

package game;

public enum GameTextState {
	GAMETEXT_MAINMENU,
	GAMETEXT_INTRO,
	GAMETEXT_GETNAME,
	GAMETEXT_GETCLASS,
	GAMETEXT_FINALIZEINTRO,
	GAMETEXT_CHAPTER1_PART1
}
